# Generated by Django 2.2.3 on 2020-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song',
            field=models.FileField(null=True, upload_to='musics/'),
        ),
    ]
