# Generated by Django 3.0.8 on 2020-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_songs_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ImageField(null=True, upload_to='album/'),
        ),
    ]
