# Generated by Django 3.0.8 on 2020-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200712_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
